volatility/plots/urls.py
from django.urls import path

from . import views

app_name = 'plots'
urlpatterns = [
    path('skew_chart/<slug:stock_symbol>', views.SkewChartView.as_view(),
         name='skew_chart'),
    path('term_structure/<slug:stock_symbol>', views.TermStructureView.as_view(),
         name='term_structure'),

    path('volatility_cones/<slug:stock_symbol>', views.VolatilityConesView.as_view(),
         name='volatility_cones'),
    path('rolling_descriptives/<slug:stock_symbol>', views.RollingDescriptivesView.as_view(),
         name='rolling_descriptives'),

    path('benchmark_comparison/<slug:stock_symbol>', views.BenchmarkComparisonView.as_view(),
         name='benchmark_comparison'),
    path('benchmark_correlation/<slug:stock_symbol>', views.BenchmarkCorrelationView.as_view(),
         name='benchmark_correlation'),

    path('universe_explorer/', views.UniverseExplorerView.as_view(),
         name='universe_explorer'),

]

volatility/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('dashboard.urls')),
    path('plots/', include('plots.urls', namespace='plots')),
    path('admin/', admin.site.urls),
]

volatility/plots/views/benchmark.py
from typing import Tuple

import pandas as pd
from bokeh.embed import components
from bokeh.layouts import column
from bokeh.models import ColumnDataSource, NumeralTickFormatter, DatetimeTickFormatter, HoverTool
from bokeh.plotting import figure
from django.shortcuts import get_object_or_404, render_to_response
from django.views import View

from calculations.estimator import get_estimator
from market_data.models import Stock
from stats.utils import get_daily_price_data


def get_daily_price_data_and_benchmark(stock: Stock, benchmark_stock: Stock
                                       ) -> Tuple[pd.DataFrame, pd.DataFrame]:
    price_data = get_daily_price_data(stock)
    benchmark = get_daily_price_data(benchmark_stock)
    # ensure stock and benchmark have the same index
    intersection = price_data.index.intersection(benchmark.index)
    price_data = price_data.loc[intersection]
    benchmark = benchmark.loc[intersection]
    return price_data, benchmark


class BenchmarkComparisonView(View):

    def get(self, request, stock_symbol):
        stock = get_object_or_404(Stock, symbol=stock_symbol)
        context = self.get_context_data(stock)
        return render_to_response('benchmark_comparison.html', context)

    def get_context_data(self, stock: Stock):
        plot = self.get_plot(stock)
        script, div = components(plot)
        return {'plot_script': script, 'plot_div': div,
                'selected_stock': stock}

    @staticmethod
    def get_plot(stock: Stock):
        benchmark_stock = Stock.get_benchmark()
        price_data, benchmark = get_daily_price_data_and_benchmark(
            stock, benchmark_stock)

        # get estimators
        window = 30
        estimator = get_estimator(
            window=window,
            price_data=price_data
        )
        benchmark_estimator = get_estimator(
            window=window,
            price_data=benchmark
        )
        dates = estimator.index

        # Create first plot
        fig1 = figure(
            title=f'GarmanKlass estimator {stock.symbol} VS {benchmark_stock.symbol} '
                  f'(daily from {dates.min()} to {dates.max()})',
            x_axis_label='Date',
            plot_width=600, plot_height=400)
        source = ColumnDataSource({'date': dates, 'current_stock': estimator,
                                   'benchmark_stock': benchmark_estimator,
                                   'ratio': estimator / benchmark_estimator})

        fig1.line(x='date', y='current_stock', legend=f'{stock}', color='red', source=source)
        fig1.line(x='date', y='benchmark_stock', legend=f'{benchmark_stock}', color='green',
                  source=source)
        fig1.legend.location = "bottom_left"
        fig1.yaxis.formatter = NumeralTickFormatter(format='0%')
        fig1.xaxis.formatter = DatetimeTickFormatter()
        fig1.add_tools(HoverTool(
            tooltips=[(stock.symbol, '@current_stock{0%}'),
                      (benchmark_stock.symbol, '@benchmark_stock{0%}'),
                      ('Date', '@date{%F}')],
            formatters={'current_stock': 'numeral', 'date': 'datetime',
                        'benchmark_stock': 'numeral'}, mode='vline'))

        # Create second plot
        fig2 = figure(title=f'Ratio', x_axis_label='Date',
                      plot_width=600, plot_height=200)
        fig2.line(x='date', y='ratio', color='blue', source=source)
        fig2.yaxis.formatter = NumeralTickFormatter(format='0 %')
        fig2.xaxis.formatter = DatetimeTickFormatter()
        fig2.add_tools(HoverTool(
            tooltips=[('Ratio', '@ratio{0%}'), ('Date', '@date{%F}')],
            formatters={'ratio': 'numeral', 'date': 'datetime'}, mode='vline'))
        # stack them
        return column(fig1, fig2)


class BenchmarkCorrelationView(View):

    def get(self, request, stock_symbol):
        stock = get_object_or_404(Stock, symbol=stock_symbol)
        context = self.get_context_data(stock)
        return render_to_response('benchmark_correlation.html', context)

    def get_context_data(self, stock: Stock):
        plot = self.get_plot(stock)
        script, div = components(plot)
        return {'plot_script': script, 'plot_div': div,
                'selected_stock': stock}

    @staticmethod
    def get_plot(stock: Stock):
        benchmark_stock = Stock.get_benchmark()
        price_data, benchmark = get_daily_price_data_and_benchmark(
            stock, benchmark_stock)

        # get estimators
        window = 30
        estimator = get_estimator(
            window=window,
            price_data=price_data
        )
        benchmark_estimator = get_estimator(
            window=window,
            price_data=benchmark
        )
        dates = estimator.index
        correlation = estimator.rolling(window=window).corr(other=benchmark_estimator)

        fig = figure(title=f'Correlation of {stock.symbol} and {benchmark_stock.symbol}'
                           f'(daily from {dates.min()} to {dates.max()})',
                     x_axis_label='Date',
                     plot_width=600, plot_height=400)
        source = ColumnDataSource({'date': dates, 'correlation': correlation})
        fig.line(x='date', y='correlation', color='blue', source=source)
        fig.yaxis.formatter = NumeralTickFormatter(format='0 %')
        fig.xaxis.formatter = DatetimeTickFormatter()
        fig.add_tools(HoverTool(
            tooltips=[('Corr.', '@correlation{0%}'), ('Date', '@date{%F}')],
            formatters={'correlation': 'numeral', 'date': 'datetime'}, mode='vline'))
        return fig

volatility/plots/views/explorer.py
from datetime import date

import pandas as pd
from bokeh.embed import components
from bokeh.models import ColumnDataSource, HoverTool
from bokeh.plotting import figure
from django.db.models import Max, Min, F, Case, When, Window, Value, Count
from django.db.models.functions import RowNumber
from django.http import HttpResponseBadRequest
from django.shortcuts import render_to_response
from django.views import View

from market_data.models import Stock, OptionQuote
from stats.models import RealizedVolatility
from plots.forms import UniverseExplorerForm
from plots.views.utils import get_expiration_dates


class UniverseExplorerView(View):

    moneyness_options = [('atm_05', 'ATM (0.5d)'), ('otm_025', 'OTM (0.25d)'),
                         ('otm_01', 'OTM (0.1d)')]

    def get(self, request):
        form = UniverseExplorerForm(request.GET)
        if form.is_valid():
            options = self.get_options()
            parameters = self.set_defaults(form, options)
            context = self.get_context_data(parameters, options)
            return render_to_response('explorer.html', context)
        else:
            return HttpResponseBadRequest(form.errors.as_json())

    def get_options(self):
        options = {}
        agg = OptionQuote.objects.aggregate(max=Max('open_interest'), min=Min('open_interest'))
        options['open_interest_range'] = dict(agg)
        agg = OptionQuote.objects.aggregate(max=Max('volume'), min=Min('volume'))
        options['volume_range'] = dict(agg)
        options['moneyness_options'] = self.moneyness_options
        options['var_options'] = [(var.name, var.description) for var in AVAILABLE_VARIABLES]
        options['expiration_dates'] = get_expiration_dates(future_only=True)
        return options

    def set_defaults(self, form, options):
        parameters = dict(form.cleaned_data)
        if not parameters['min_open_interest']:
            parameters['min_open_interest'] = options['open_interest_range']['min']
        if not parameters['min_volume']:
            parameters['min_volume'] = options['volume_range']['min']
        if not parameters['min_expiration_date']:
            parameters['min_expiration_date'] = date.today()
        if not parameters['moneyness']:
            parameters['moneyness'] = options['moneyness_options'][0][0]
        if not parameters['x_var']:
            parameters['x_var'] = AVAILABLE_VARIABLES[0].name
        if not parameters['y_var']:
            parameters['y_var'] = AVAILABLE_VARIABLES[1].name
        return parameters

    def get_context_data(self, parameters, options):
        plot = self.get_plot(**parameters)
        script, div = components(plot)
        context = {'plot_script': script, 'plot_div': div,
                   'selected_open_interest': parameters['min_open_interest'],
                   'selected_volume': parameters['min_volume'],
                   'selected_expiration_date': parameters['min_expiration_date'],
                   'selected_moneyness': parameters['moneyness'],
                   'selected_x_var': parameters['x_var'],
                   'selected_y_var': parameters['y_var']}
        context.update(options)
        return context

    @staticmethod
    def get_plot(x_var, y_var, **parameters):
        x_variable = ExplorerVariable.get_by_name(x_var)
        y_variable = ExplorerVariable.get_by_name(y_var)
        if x_variable.name == y_variable.name:
            data = x_variable.get_stocks_data(**parameters).to_frame()
        else:
            data = pd.concat([x_variable.get_stocks_data(**parameters),
                              y_variable.get_stocks_data(**parameters)],
                             axis=1, sort=True)
        data.index.name = 'symbol'

        source = ColumnDataSource(data)
        plot = figure(title=f'Universe explorer',
                      x_axis_label=x_variable.description,
                      y_axis_label=y_variable.description)
        # Add big white circles for better hover tool experience
        plot.circle(x=x_variable.name, y=y_variable.name, color='white', size=30, source=source)
        plot.circle(x=x_variable.name, y=y_variable.name, size=5, source=source)
        plot.add_tools(HoverTool(tooltips=[
            (x_variable.description, f'@{x_variable.name}'),
            (y_variable.description, f'@{y_variable.name}'),
            ('Stock', f'@{data.index.name}')]))
        return plot


class ExplorerVariable:
    """
    Base class for variable in universe explorer.

    User can select two variables there (one foe x axis and one for y).
    This class represents a single option.
    """

    # internal identifier
    name = 'variable'
    # representation for user
    description = 'Variable Description'

    @classmethod
    def get_stocks_data(cls, min_open_interest: float, min_volume: float,
                        min_expiration_date: date, moneyness: float) -> pd.Series:
        """
        Return variable values for each stock.

        arguments are user specified parameters in interface.
        return value should be a pandas.Series with stock symbol as index.
        """
        raise NotImplementedError

    @classmethod
    def get_by_name(cls, name):
        for klass in cls.__subclasses__():
            if klass.name == name:
                return klass
            # check all subclasses recursively
            subclass = klass.get_by_name(name)
            if subclass is not None:
                return subclass
        else:
            return None


class BaseImpliedVolatilityVariable(ExplorerVariable):
    """Base class for put and call implied volatility variables."""

    option_type = 'type'

    @staticmethod
    def get_delta(moneyness):
        raise NotImplementedError

    @classmethod
    def get_stocks_data(cls, min_open_interest: float, min_volume: float,
                        min_expiration_date: date, moneyness: str) -> pd.Series:
        stocks_count = Stock.objects.count()
        delta = cls.get_delta(moneyness)
        qs = (OptionQuote.objects
              .filter(volume__gte=min_volume,
                      open_interest__gte=min_open_interest,
                      type=cls.option_type,
                      expiration_date__gte=min_expiration_date)
              .annotate(distance=Case(
                # distance = ABS(delta_greek - delta)
                When(stats__delta_greek__gte=delta, then=F('stats__delta_greek') - delta),
                When(stats__delta_greek__lt=delta, then=delta - F('stats__delta_greek')),
              ))
              # we need to find a quote with the nearest delta
              # so we calculate row_number(OVER distance PARTITION BY stock_id)
              # and then select records with row_number = 1
              .annotate(row_number=Window(
                expression=RowNumber(),

                partition_by=[F('stock_id')],
                order_by=F('distance').asc(),
              ))
              # it's a bit hackish. django doesn't allow to filter by window functions
              # but we know how many records there should be (the same as number of stock)
              # so we order by row_number
              .order_by('row_number')[:stocks_count]
              # and take N first records
              .values('stock__symbol', 'stats__implied_volatility', 'row_number'))
        df = (pd.DataFrame.from_records(qs))
        # some stocks can have no records for specified filters, filter them in python
        df = df[df['row_number'] == 1].drop('row_number', axis=1)
        df = (df.rename(columns={'stock__symbol': 'symbol', 'stats__implied_volatility': cls.name})
              .set_index('symbol'))[cls.name]
        return df


class PutImpliedVolatilityVariable(BaseImpliedVolatilityVariable):

    name = 'put_iv'
    description = 'Put I.V.'

    option_type = OptionQuote.PUT

    @staticmethod
    def get_delta(moneyness):
        # put options have negative deltas, for them we need to inverse sign
        if moneyness == 'atm_05':
            return -0.5
        elif moneyness == 'otm_025':
            return -0.25
        elif moneyness == 'otm_01':
            return -0.1


class CallImpliedVolatilityVariable(BaseImpliedVolatilityVariable):

    name = 'call_iv'
    description = 'Call I.V.'

    option_type = OptionQuote.CALL

    @staticmethod
    def get_delta(moneyness):
        # return moneyness as is
        if moneyness == 'atm_05':
            return 0.5
        elif moneyness == 'otm_025':
            return 0.25
        elif moneyness == 'otm_01':
            return 0.1


class PutCallImpliedVolatilityVariable(ExplorerVariable):

    name = 'put_call_iv'
    description = 'Put+Call I.V.'

    @classmethod
    def get_stocks_data(cls, **parameters) -> pd.Series:
        put = PutImpliedVolatilityVariable.get_stocks_data(**parameters)
        call = CallImpliedVolatilityVariable.get_stocks_data(**parameters)
        result = (put + call) / 2
        result.name = cls.name
        return result


class BaseIVPercentileVariable(ExplorerVariable):

    underlying_variable = BaseImpliedVolatilityVariable
    option_types = ['type']

    @classmethod
    def get_stocks_data(cls, **parameters) -> pd.Series:
        current_values = cls.underlying_variable.get_stocks_data(**parameters)
        # find number of records where given value is greater then historical
        qs = (OptionQuote.objects
              .filter(type__in=cls.option_types)
              .annotate(diff=Case(
                *[When(stock__symbol=symbol,
                       then=Value(current_value) - F('stats__implied_volatility'))
                  for symbol, current_value in current_values.iteritems()]
               ))
              .filter(diff__gte=0)
              .values('stock__symbol')
              .annotate(partial=Count('id')))
        partial = (pd.DataFrame.from_records(qs)
                   .rename(columns={'stock__symbol': 'symbol'})

volatility/plots/views/utils.py
from datetime import date

from functools import lru_cache
from typing import List

from market_data.models import Stock, OptionQuote


@lru_cache(maxsize=32)
def get_expiration_dates(stock: Stock = None, future_only=False) -> List[date]:
    """Return a list of available expiration dates in database."""
    qs = OptionQuote.objects.all()
    if stock is not None:
        qs = qs.filter(stock=stock)
    if future_only:
        qs = qs.filter(expiration_date__gt=date.today())
    return list(qs.distinct('expiration_date')
                .order_by('expiration_date')
                .values_list('expiration_date', flat=True))

volatility/plots/templates/benchmark_comparison.html
<div id="benchmark_comparison_plot">
    {{ plot_div | safe}}
    {{ plot_script | safe}}
</div>

volatility/plots/templates/benchmark_correlation.html
<div id="benchmark_correlation_plot">
    {{ plot_div | safe}}
    {{ plot_script | safe}}
</div>

volatility/plots/templates/explorer.html
{% load jsonify %}
{% load static %}
<div id="universe_explorer_plot" class="row">
    <nav class="col-md-2 d-none d-md-block bg-light sidebar">
        <p style="margin-bottom: 0; margin-top: 15px">Open interest</p>
        <input type="text" class="js-range-slider" value="" id="open-interest-slider"/>
        <p style="margin-bottom: 0; margin-top: 15px">Volume</p>
        <input type="text" class="js-range-slider" value="" id="volume-slider"/>
        <p style="margin-bottom: 0; margin-top: 15px">Min expiration date</p>
        <div id="datepicker">
            <div class="input-group date">
                <input value="{{ selected_expiration_date | jsonify | cut:'"' }}" type="text" class="form-control">
                <div class="input-group-addon">
                    <span class="oi oi-calendar" style="font-size: 36px"></span>
                </div>
            </div>
        </div>
        <p style="margin-bottom: 0; margin-top: 15px">Moneyness</p>
        <select id="moneyness-selector">
            {% for id, text in moneyness_options %}
                {% if id == selected_moneyness %}
                    <option value="{{ id }}" selected="selected">{{ text }}</option>
                {% else %}
                    <option value="{{ id }}">{{ text }}</option>
                {% endif %}
            {% endfor %}
        </select>
        <p style="margin-bottom: 0; margin-top: 15px">X variable</p>
        <select id="x-var-selector" style="width: 120px">
            {% for id, text in var_options %}
                {% if id == selected_x_var %}
                    <option value="{{ id }}" selected="selected">{{ text }}</option>
                {% else %}
                    <option value="{{ id }}">{{ text }}</option>
                {% endif %}
            {% endfor %}
        </select>
        <p style="margin-bottom: 0; margin-top: 15px">Y variable</p>
        <select id="y-var-selector" style="width: 120px">
            {% for id, text in var_options %}
                {% if id == selected_y_var %}
                    <option value="{{ id }}" selected="selected">{{ text }}</option>
                {% else %}
                    <option value="{{ id }}">{{ text }}</option>
                {% endif %}
            {% endfor %}
        </select>
    </nav>
    <div class="col-md-offset-2">
        {{ plot_div | safe}}
        {{ plot_script | safe}}
    </div>
</div>
{# Pass variables from django to javascript #}
<div style="visibility: hidden" id="open-interest-range">{{ open_interest_range | jsonify }}</div>
<div style="visibility: hidden" id="volume-range">{{ volume_range | jsonify }}</div>
<div style="visibility: hidden" id="expiration-dates">{{ expiration_dates | jsonify }}</div>
<div style="visibility: hidden" id="selected-open-interest">{{ selected_open_interest | jsonify }}</div>
<div style="visibility: hidden" id="selected-volume">{{ selected_volume | jsonify }}</div>
<div style="visibility: hidden" id="selected-expiration-date">{{ selected_expiration_date | jsonify }}</div>
<div style="visibility: hidden" id="selected-moneyness">{{ selected_moneyness | jsonify }}</div>
<div style="visibility: hidden" id="selected-x-var">{{ selected_x_var | jsonify }}</div>
<div style="visibility: hidden" id="selected-y-var">{{ selected_y_var | jsonify }}</div>

{# Call the loader from explorer.js #}
<script>load_universe_explorer();</script>
<script>

</script>

volatility/plots/templates/rolling_descriptives.html
<div id="rolling_descriptives_plot">
    <a>Select window</a>
    <select id="window_selector" style="width: 120px">
        {% for id, text in window_options %}
            {% if id == selected_window %}
                <option value="{{ id }}" selected="selected">{{ text }}</option>
            {% else %}
                <option value="{{ id }}">{{ text }}</option>
            {% endif %}
        {% endfor %}
    </select>
    {{ plot_div | safe}}
    {{ plot_script | safe}}
</div>
<script>
    $('#window_selector').select2({
        'width': 'style'
    }).on('select2:select', function (e){
        var window = e.params.data.id;
        let rolling_descriptives_url = "{% url 'plots:rolling_descriptives' stock_symbol=selected_stock.symbol %}?window=" + window;
        $("#rolling_descriptives_plot").load(rolling_descriptives_url)
    });
</script>

volatility/plots/templates/skew_chart.html
<div id="implied_volatility_plot">
    <div id="datepicker">
        <div class="input-group date">
            <input type="hidden" placeholder="Choose expiration date" value="{{ selected_dates }}" style="width: 0">
            <div class="input-group-addon">
                <span class="oi oi-calendar" style="font-size: 36px"></span>
            </div>
            <a style="font-size: 20px; padding-left: 10px">Add expiration dates</a>
        </div>
    </div>
    {{ plot_div | safe}}
    {{ plot_script | safe}}
</div>
<div style="visibility: hidden" id="available-dates">{{ available_dates }}</div>

<script>
    function formatDate(date) {
      var day = date.getDate();
      var monthIndex = date.getMonth();
      var year = date.getFullYear();

      return year + '-' + (monthIndex + 1)+ '-' + day ;
    }
    var availableDates = $("#available-dates").text().split(',').filter(
        function(e){return e}
    ).map(
        function(param) {
            return formatDate(new Date(param));
        }
    );

    $('#datepicker .input-group.date').datepicker({
        format: 'yyyy-m-d',
        autoclose: true,
        multidate: true,
        beforeShowDay: function(date) {
            return $.inArray(formatDate(date), availableDates) != -1;
        }
    }).on('changeDate', function(ev) {
        let selected_dates = $('#datepicker .input-group.date').datepicker('getDates');
        let formatted = selected_dates.map(formatDate);
        let $implied_volatility_url = "{% url 'plots:skew_chart' stock_symbol=selected_stock.symbol %}?expiration_dates=" + formatted;
        $("#implied_volatility_plot").load($implied_volatility_url);

    });
</script>

volatility/plots/templates/term_structure.html
<div id="term_structure_plot">
    Select <b>strike</b> value
    <input type="text" class="js-range-slider" name="my_range" value="" id="strike_range_slider"/>
    {{ plot_div | safe}}
    {{ plot_script | safe}}
    <div style="visibility: hidden" id="available-strikes">{{ available_strikes }}</div>
    <div style="visibility: hidden" id="selected-strike">{{ selected_strike }}</div>
</div>



<script>
    var availableStrikes = $("#available-strikes").text().split(',').filter(
        function(e){return e}
    ).map(
        function(param) {
            return parseFloat(param);
        }
    );
    var selectedStrike = parseFloat($("#selected-strike").text());
    var selectedStrikeId = availableStrikes.indexOf(selectedStrike)

    $("#strike_range_slider").ionRangeSlider({
        grid: true,
        from: selectedStrikeId,
        values: availableStrikes,
        onFinish: function (data) {
            let strike = data.from_value;
            let term_structure_url = "{% url 'plots:term_structure' stock_symbol=selected_stock.symbol %}?strike=" + strike;
            $("#term_structure_plot").load(term_structure_url);
        },
    });
</script>

volatility/plots/templates/volatility_cones.html
<div id="volatility_cones_plot">
    {{ plot_div | safe}}
    {{ plot_script | safe}}
</div>